### PR TITLE
Increment the version we depend on of the multilang-extract-comments 

### PR DESCRIPTION
**Pull request by seancsnyder**
We need to update the version we depend upon for a dependency. Some recent enhancements have been made...

### CODE REVIEW

**Comment by seancsnyder** [comment]
Can I get some eyes on this PR? @haroldtreen @gkoberger @gaofei88

**Comment by seancsnyder** [comment]
Also tagging @domharrington and @mjcuva to take a look for getting this merged in

**Comment by domharrington** [comment]
Thanks @seancsnyder. Let me know if this is resolved now.

**Comment by seancsnyder** [comment]
Thanks! I'll let you know.

**Comment by seancsnyder** [comment]
Confirmed resolved.

**Pull request merged**
